### ISSUE TITLE
UmbracoExamine.PDF v1.0.3: System.IO.FileNotFoundException at UmbracoExamine.PDF.PDFParser.GetTextFromAllPages()

### ISSUE THREAD

**Issue by timeverts** [umbraco/UmbracoExamine.PDF#24]
Hi @Shazwazza,

I'm running UmbracoExamine.PDF v1.0.3 on Umbraco 7.15.6.

I am seeing the following error logged:
```
An error occurred: System.IO.FileNotFoundException: Could not load file or assembly 'itextsharp, Version=5.5.5.0, Culture=neutral, PublicKeyToken=8354ae6d2174ddca' or one of its dependencies. The system cannot find the file specified.
File name: 'itextsharp, Version=5.5.5.0, Culture=neutral, PublicKeyToken=8354ae6d2174ddca'
   at UmbracoExamine.PDF.PDFParser.GetTextFromAllPages(String pdfPath, MediaFileSystem mediaFileSystem, Action`1 onError)
   at UmbracoExamine.PDF.PDFIndexer.ExtractTextFromFile(String filePath, MediaFileSystem mediaFileSystem) in c:\Users\Shannon\Documents\_Projects\Umbraco\UmbracoExamine.PDF\src\UmbracoExamine.PDF\PDFIndexer.cs:line 146
   at UmbracoExamine.PDF.PDFIndexer.GetDataToIndex(XElement node, String type) in c:\Users\Shannon\Documents\_Projects\Umbraco\UmbracoExamine.PDF\src\UmbracoExamine.PDF\PDFIndexer.cs:line 206

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

If you have a moment, can you please investigate.

I believe the indexer is still working, but it is encountering this issue for PDFs that are not found.

**Comment by Shazwazza** [comment]
Sounds like the package isn't installed correctly or it's missing the itextsharp.dll file. If you've installed by Nuget then it will be there automatically. Check your /bin folder, else try reinstalling the package. Or it could be that you need assembly binding redirects to the itextsharp version that is installed since 5.5.5 is pretty old.

**Comment by timeverts** [comment]
Thanks @Shazwazza. It was a missing binding redirect by the looks of it.
